name: Build, Test and Publish

on:
  push:
    branches: [main]
    tags: [v*]
  pull_request:
    branches: [main]

env:
  DOTNET_VERSION: 8.x

jobs:
  build-and-test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Output version of .NET
        run: dotnet --version
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        id: test
        run: dotnet test --configuration Release --no-build --verbosity normal --collect:"XPlat Code Coverage" --results-directory ./coverage
      - name: Check code coverage
        uses: Thomas-Shephard/coverage-checker@v0.6.1
        with:
          format: 'Cobertura'
          glob-pattern: 'coverage/**/coverage.cobertura.xml'
          line-threshold: 100
          branch-threshold: 100
  publish-nuget-package:
    if: startsWith(github.ref, 'refs/tags/v')
    name: Publish NuGet Package
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup .NET ${{ env.DOTNET_VERSION }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}
      - name: Output version of .NET
        run: dotnet --version
      - name: Add GitHub source
        run: dotnet nuget add source "https://nuget.pkg.github.com/Thomas-Shephard/index.json" --name "github.com" --username "Thomas-Shephard" --password ${{ secrets.PUBLISH_TO_GITHUB_TOKEN }} --store-password-in-clear-text
      - name: Pack project
        run: dotnet pack DocumentationCommentsAnalyzer/DocumentationCommentsAnalyzer /p:PackageVersion=${GITHUB_REF_NAME#v} --configuration Release
      - name: Push to sources
        run: |
          dotnet nuget push **/*.nupkg --source "github.com"
          dotnet nuget push **/*.nupkg --api-key ${{ secrets.PUBLISH_TO_NUGET_TOKEN }} --source "nuget.org"